// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Content for calendar documents
 */
interface CalendarDocumentData {
  /**
   * header field in *calendar*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: calendar.header
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  header: prismic.ContentRelationshipField<"calendar_header">;

  /**
   * banner field in *calendar*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: calendar.banner
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  banner: prismic.ContentRelationshipField<"calendar_banner">;
}

/**
 * calendar document from Prismic
 *
 * - **API ID**: `calendar`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CalendarDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<CalendarDocumentData>,
    "calendar",
    Lang
  >;

/**
 * Content for calendar_banner documents
 */
interface CalendarBannerDocumentData {
  /**
   * title field in *calendar_banner*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Título
   * - **API ID Path**: calendar_banner.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * subtitle field in *calendar_banner*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Subtitulo
   * - **API ID Path**: calendar_banner.subtitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;
}

/**
 * calendar_banner document from Prismic
 *
 * - **API ID**: `calendar_banner`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CalendarBannerDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<CalendarBannerDocumentData>,
    "calendar_banner",
    Lang
  >;

/**
 * Content for calendar_header documents
 */
interface CalendarHeaderDocumentData {
  /**
   * title field in *calendar_header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Título
   * - **API ID Path**: calendar_header.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * subtitle field in *calendar_header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Subtitulo
   * - **API ID Path**: calendar_header.subtitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;
}

/**
 * calendar_header document from Prismic
 *
 * - **API ID**: `calendar_header`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CalendarHeaderDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<CalendarHeaderDocumentData>,
    "calendar_header",
    Lang
  >;

export type AllDocumentTypes =
  | CalendarDocument
  | CalendarBannerDocument
  | CalendarHeaderDocument;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      CalendarDocument,
      CalendarDocumentData,
      CalendarBannerDocument,
      CalendarBannerDocumentData,
      CalendarHeaderDocument,
      CalendarHeaderDocumentData,
      AllDocumentTypes,
    };
  }
}
